[build]
  # No build command needed for static site
  command = "echo 'Static site deployment - no build required'"
  
  # Publish directory - where your main HTML files are located
  publish = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Authentication and OAuth redirects - HIGHEST PRIORITY
[[redirects]]
  from = "/redirect-handler*"
  to = "/redirect-handler.html"
  status = 200
  force = true

# Ensure OAuth callbacks go directly to redirect-handler
[[redirects]]
  from = "/#*"
  to = "/redirect-handler.html"
  status = 200
  conditions = {Query = {access_token = ":access_token"}}

[[redirects]]
  from = "/#*"
  to = "/redirect-handler.html"
  status = 200
  conditions = {Query = {token_type = ":token_type"}}

[[redirects]]
  from = "/*"
  to = "/redirect-handler.html"
  status = 200
  conditions = {Query = {code = ":code"}}

# Auth pages
[[redirects]]
  from = "/auth*"
  to = "/html/auth.html"
  status = 200
  force = true

# Dashboard routes - SECOND PRIORITY
[[redirects]]
  from = "/user-dashboard*"
  to = "/html/user-dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard*"
  to = "/html/user-dashboard.html"
  status = 200
  force = true

# Static pages
[[redirects]]
  from = "/privacy-policy*"
  to = "/html/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-use*"
  to = "/html/terms-of-use.html"
  status = 200

# Static assets
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# API routes (if any)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all for unknown routes - LOWEST PRIORITY
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://accounts.google.com https://apis.google.com https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://accounts.google.com https://oauth2.googleapis.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]  
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Special headers for auth pages
[[headers]]
  for = "/html/auth.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/redirect-handler.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/html/user-dashboard.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Environment variables (these should be set in Netlify dashboard)
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key" 